version: "3.8"

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    # Montamos el código para hot-reload
    volumes:
      - ./back/app:/app/app
      - ./back/pyproject.toml:/app/pyproject.toml
      # - ./back/poetry.lock:/app/poetry.lock
    ports:
      - "8000:8000"
    environment:
      # Para que Uvicorn recargue con cambios
      - UVICORN_RELOAD=true
    command: >
      uvicorn app.main:app
        --host 0.0.0.0
        --port 8000
        ${UVICORN_RELOAD:+--reload}

