version: '3.8'

services:
  api-gateway:
    build: ./apiGateway
    ports:
      - "8080:8080"
    depends_on:
      - order-service
      - reservation-service

  order-service:
    build: ./order-service
    # No es necesario exponer puertos externamente para pruebas básicas

  reservation-service:
    build: ./reservation-service